### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by omern8878** [nithin-baby/js-xlsx-style#2]
Hey, 
I'm trying to use hyperlinks to the cell (like this: cell.l= { Target: somelink, Tooltip:'blabla'}). It used to work when I only used xlsx but it stopped working when I was adding xlsx-style.

**Comment by omern8878** [comment]
I also tried using a formula and it prints undefined. Code ex:
 cell.f = '=HYPERLINK("link", "name")'
Tried also 
cell.f = 'HYPERLINK("link", "name")'
Those are printing undefined

**Comment by ghost** [comment]
xlsx-style may not contain the latest updates in js-xlsx. Also from the xlsx-style repo https://github.com/protobi/js-xlsx, I see that it was last updated on May 31st, 2017. You can try using the latest available version or raise an issue in the js-xlsx GitHub repo. This repo was intended only as a demo and I don't have any ownership for xlsx-style code.
